chrome_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
chrome_args = ["--user-data-dir=/Users/singhpra/Trading/ChromeDataDir"]

log_config = "info,headless_chrome=warn,stock_themes=debug"

stock_store_file = "stock_store.toml"
